ignoredBuiltDependencies:
  - bufferutil

packages:
  - "packages/scramjet"
  - "packages/chrome"
  - "packages/cdp"
  - "packages/devtools"
  - "packages/sandbox"
  - "packages/inject"
  - "external/dreamlandjs"
