name: WPT-diff Tests

on:
  schedule:
    # Every night at 0:30 UTC
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build Scramjet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: install wbg
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: 0.2.100

      - name: Setup Binaryen
        uses: Aandreba/setup-binaryen@v1.0.0
        with:
          token: ${{ github.token }}

      - name: Setup wasm-snip
        run: cargo install --git https://github.com/r58playz/wasm-snip

  wpt-diff:
    name: Run WPT-diff Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: scramjet
          path: dist

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Run the Scramjet Demo
        run: |
          pnpm start &
          DEMO_PID=$!
          echo "DEMO_PID=$DEMO_PID" >> $GITHUB_ENV
          sleep 10

      - name: Checkout WPT-diff
        uses: actions/checkout@v4
        with:
          repository: MercuryWorkshop/WPT-diff
          path: wpt-diff-repo
          submodules: recursive

      - name: Run WPT-Diff
        uses: ./wpt-diff-repo/.github/actions/wpt_diff
        with:
          proxyName: scramjet
          wpt_max_tests: 999999999
          wpt_tests_base_url: http://web-platform.test:8000
          wpt_api_base_url: https://wpt.fyi
          under_proxy: "true"

      - name: Kill Scramjet Demo
        if: always()
        run: |
          if [ ! -z "$DEMO_PID" ]; then
            kill $DEMO_PID || true
          fi
