name: WPT-diff Tests

on:
  schedule:
    # Every night at 0:30 UTC
    - cron: "30 0 * * *"
  workflow_dispatch:
    inputs:
      test_mode:
        description: "Run in test mode (fewer shards)"
        required: false
        default: true
        type: boolean

jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}

    steps:
      - name: Checkout Scramjet
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for recent changes
        id: check
        run: |
          # Check if there were any commits in the last day
          SCRAMJET_CHANGED=$(git log --since="24 hours ago" --oneline | wc -l)

          # Check WPT-diff repo
          git clone --shallow-since="24 hours ago" https://github.com/MercuryWorkshop/WPT-diff.git wpt-diff-check
          cd wpt-diff-check
          WPTDIFF_CHANGED=$(git log --since="24 hours ago" --oneline | wc -l)
          cd ..

          # Check WPT upstream
          # They are always committing (it must be the final hours of the world when they don't)
          git clone --shallow-since="24 hours ago" https://github.com/web-platform-tests/wpt.git wpt-check
          cd wpt-check
          WPT_CHANGED=$(git log --since="24 hours ago" --oneline | wc -l)
          cd ..

          # Run tests if any repo has changes or if manually triggered
          if [ "$SCRAMJET_CHANGED" -gt 0 ] || [ "$WPTDIFF_CHANGED" -gt 0 ] || [ "$WPT_CHANGED" -gt 0 ] || [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "should-run=true" >> "$GITHUB_OUTPUT"
            echo "Changes detected or manually triggered (will run tests)"
          else
            echo "should-run=false" >> "$GITHUB_OUTPUT"
            echo "No changes detected (skipping tests)"
          fi

  build:
    name: Build Scramjet for WPT-diff
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.should-run == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: install wbg
        uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: 0.2.100

      - name: Setup Binaryen
        uses: Aandreba/setup-binaryen@v1.0.0
        with:
          token: ${{ github.token }}

      - name: Setup wasm-snip
        run: "cargo install --git https://github.com/r58playz/wasm-snip"

      - name: Pack Scramjet
        run: pnpm pack

      - name: Upload Artifact (pnpm pack)
        uses: actions/upload-artifact@v4
        with:
          name: packaged-scramjet
          path: mercuryworkshop-scramjet-*.tgz

      - name: Upload Artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: scramjet
          path: |
            dist/*.js
            dist/*.js.map
            dist/*.wasm

  wpt-diff:
    name: Run WPT-diff Tests (Shard ${{ matrix.shard }})
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 350
    strategy:
      fail-fast: true
      matrix:
        shard: ${{ fromJSON(github.event.inputs.test_mode == 'true' && '[0, 1]' || '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pnpm install

      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: scramjet
          path: dist

      - name: Start demo server
        run: |
          pnpm start &
          DEMO_PID=$!
          echo "DEMO_PID=$DEMO_PID" >> "$GITHUB_ENV"
          sleep 10

      - name: Checkout WPT-diff
        uses: actions/checkout@v4
        with:
          repository: MercuryWorkshop/WPT-diff
          path: wpt-diff

      - name: Checkout Web Platform Tests
        uses: actions/checkout@v4
        with:
          repository: web-platform-tests/wpt
          ref: main
          path: wpt-diff/wpt
          fetch-depth: 1

      - name: Setup WPT hosts
        run: |
          cd wpt-diff/wpt
          ./wpt make-hosts-file | sudo tee -a /etc/hosts

      - name: Restore Playwright browsers cache
        id: playwright-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/Library/Caches/ms-playwright
            C:\\Users\\runneradmin\\AppData\\Local\\ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('wpt-diff/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies and setup
        run: |
          cd wpt-diff
          pnpm install
          # Install Playwright browsers only if cache miss
          if [ "${{ steps.playwright-cache.outputs.cache-hit }}" != 'true' ]; then
            pnpm exec playwright install chromium
          fi
          pnpm generate:validators

      - name: Save Playwright browsers cache
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/Library/Caches/ms-playwright
            C:\\Users\\runneradmin\\AppData\\Local\\ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('wpt-diff/pnpm-lock.yaml') }}

      - name: Generate WPT-Diff config
        working-directory: wpt-diff
        run: |
          cat > config.toml << EOF
          [debug]
          debug = true
          verbose = true

          [wpt]
          max_tests = "all"
          under_proxy = true

          [wpt.urls]
          proxy_base_url = "http://localhost:1337/"
          tests_base_url = "http://web-platform.test:8000"
          api_base_url = "https://wpt.fyi"
          EOF

      - name: Start WPT server
        working-directory: wpt-diff/wpt
        run: |
          ./wpt serve --no-h2 &
          echo "WPT_PID=$!" >> $GITHUB_ENV
          sleep 10

      - name: Run WPT-Diff shard
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            cd wpt-diff
            export CI=true
            pnpm start \
              --report wpt-report.json \
              --output-failed failed-tests.json \
              --shard ${{ matrix.shard }} \
              --total-shards ${{ github.event.inputs.test_mode == 'true' && '2' || '10' }}

      - name: Kill Scramjet Demo
        if: always()
        run: |
          if [ -n "$DEMO_PID" ]; then
            kill "$DEMO_PID" || true
          fi

      - name: Stop WPT server
        if: always()
        run: |
          if [ -n "$WPT_PID" ]; then
            kill "$WPT_PID" || true
          fi

      - name: Upload shard artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wpt-shard-results-${{ matrix.shard }}
          path: |
            wpt-diff/wpt-report.json
            wpt-diff/failed-tests.json

  combine-reports:
    name: Combine and upload final reports
    runs-on: ubuntu-latest
    needs: wpt-diff
    if: always() && needs.wpt-diff.result != 'cancelled'

    steps:
      - name: Checkout WPT-diff
        uses: actions/checkout@v4
        with:
          repository: MercuryWorkshop/WPT-diff
          path: wpt-diff

      - name: Combine reports and run regression check
        uses: ./wpt-diff/
        with:
          location: wpt-diff
          enable_regression_check: false
          github_repository: MercuryWorkshop/WPT-diff
          github_token: ${{ secrets.GITHUB_TOKEN }}
          regression_check_workflow_name: "WPT-diff Tests"
          artifact_name: wpt-diff-reports
